name: test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: golang setup
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: golang build
        run: go build -v ./...

      - name: setup kubernetes
        env:
          KUBECONFIG_BASE64: ${{secrets.KUBECONFIG_BASE64}}
        run: |
          mkdir -p $HOME/.kube
          echo "${KUBECONFIG_BASE64}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: golang test
        run: go test -v ./...
